name: Build and Upload to SquareCloud - Front-end

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Show system info
        run: |
          node -v
          npm -v
          free -h

      - name: Clear npm cache and node_modules
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: |
          npm install --production=false --legacy-peer-deps
          npm list --prod --depth=0

      - name: Build application
        env:
          CI: false
          NODE_ENV: production
          NODE_OPTIONS: --max-old-space-size=8192 --max-semi-space-size=512 --optimize-for-size
          GENERATE_SOURCEMAP: false
          INLINE_RUNTIME_CHUNK: false
          IMAGE_INLINE_SIZE_LIMIT: 0
          DISABLE_ESLINT_PLUGIN: true
          TSC_COMPILE_ON_ERROR: true
          FAST_REFRESH: false
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm run build --verbose

      - name: Analyze build output
        run: ls -lh build/static/js/

  deploy:
    needs: build
    uses: sheila-garcia-pro/pipeline-deploy/.github/workflows/deploy.yml@main
    secrets:
      SQUARE_API_KEY: ${{ secrets.SQUARE_CLOUD_TOKEN }}
      API_ID_KEY: ${{ secrets.API_ID }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
