name: Build and Upload to SquareCloud - Front-end

on:
  push:
    branches:
      - main
env:
  NODE_OPTIONS: --max-old-space-size=8192
  CI: false

jobs:
  deploy:
    uses: sheila-garcia-pro/pipeline-deploy/.github/workflows/deploy.yml@main
    secrets:
      SQUARE_API_KEY: ${{ secrets.SQUARE_CLOUD_TOKEN }}
      API_ID_KEY: ${{ secrets.API_ID }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
