name: Build and Upload to SquareCloud - Front-end.

on:
  push:
    branches:
      - main
      - dev
      
jobs:     
  deploy:
    uses: sheila-garcia-pro/pipeline-deploy/.github/workflows/deploy.yml@main
    secrets:
      SQUARE_API_KEY: ${{ github.ref_name == 'main' && secrets.TOKEN_SQUARE_CLOUD_SHEILA || secrets.SQUARE_CLOUD_TOKEN }}
      API_ID_KEY: ${{ github.ref_name == 'main' && secrets.APP_ID_PROD || secrets.API_ID }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
