name: Build and Upload to SquareCloud - Front-end

on:
  push:
    branches:
      - main
env:
  NODE_OPTIONS: --max-old-space-size=16384
  CI: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure npm
        run: |
          mkdir -p ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          npm install -g npm@latest

  deploy:
    needs: setup
    uses: sheila-garcia-pro/pipeline-deploy/.github/workflows/deploy.yml@main
    secrets:
      SQUARE_API_KEY: ${{ secrets.SQUARE_CLOUD_TOKEN }}
      API_ID_KEY: ${{ secrets.API_ID }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
