name: Build and Upload to SquareCloud - Front-end

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'
          cache: 'npm'

      - name: Update npm
        run: npm install -g npm@11.4.1

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit
          npm dedupe

      - name: Analyze bundle
        run: npm install -g webpack-bundle-analyzer

      - name: Build application (part 1 - vendor)
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          CI: false
          GENERATE_SOURCEMAP: false
          REACT_APP_BUILD_PART: vendor
        run: npm run build

      - name: Build application (part 2 - app)
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          CI: false
          GENERATE_SOURCEMAP: false
          REACT_APP_BUILD_PART: app
        run: npm run build

  deploy:
    needs: build
    uses: sheila-garcia-pro/pipeline-deploy/.github/workflows/deploy.yml@main
    secrets:
      SQUARE_API_KEY: ${{ secrets.SQUARE_CLOUD_TOKEN }}
      API_ID_KEY: ${{ secrets.API_ID }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
